# Generated by Django 5.2.1 on 2025-07-21 12:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exams", "0004_alter_unscheduledexam_created_at"),
        ("sharedapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="unscheduledexam",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="unscheduledexam",
            name="groups",
            field=models.ManyToManyField(
                blank=True, null=True, to="sharedapp.unscheduledexamgroup"
            ),
        ),
    ]
